# Generated by Django 3.1 on 2020-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_categorymodel_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='student_app/images/')),
            ],
        ),
    ]
